import type { Spelldata } from "./types";

export const charClasses: string[] = [
  "",
  "Artificer",
  "Barbarian",
  "Bard",
  "Cleric",
  "Druid",
  "Fighter",
  "Monk",
  "Paladin",
  "Ranger",
  "Rogue",
  "Sorcerer",
  "Warlock",
  "Wizard",
];

export const customData: Spelldata[] = [
  {
    spell_name: "Notes",
    level: 10,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description:
      "Text of spells can also be found here: http://dnd2024.wikidot.com/spell:all",
    material: null,
    school: null,
    classes: null,
    id: "4e1a9b66",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Custom Spell Name",
    level: 10,
    range: "60 feet",
    components: "V, S, M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "1 Action",
    ritual: true,
    description:
      "This is a spell description. It is written in markdown. Use ctrl+enter or ⌘+return to insert a line break.\n\nThis is a list: \n\n* List item 1\n* List item 2\n\n### This is a heading and below is a table:\n\n| Column heading 1 | Column heading 2 |\n| :--------------: | ---------------- |\n|       value      | value            |\n|       value      | value            |\n|       value      | value            |\n\n**This is bold.** This is not.\n\n_This is italic._",
    material: null,
    school: "Transmutation",
    classes: "Sorcerer, Wizard",
    id: "d30ae05d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Example Spell",
    level: 10,
    range: "60 feet",
    components: "V, M",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Reaction",
    ritual: false,
    description:
      "_Take this reaction when you or a creature you can see within 60 feet of you lorem ipsum._ \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna eu erat mattis eleifend quis ac risus. Nullam venenatis mauris ac orci hendrerit porta.\n\n**Using a Higher-Level Spell Slot.** Lorem ipsum 1d6 erat mattis eleifend quis ac risus.",
    material: "A pinch of dust",
    school: "Divination",
    classes: "Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Warlock, Wizard",
    id: "00d8e982",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Friends",
    level: 0,
    range: "10 feet",
    components: "S, M",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "You magically emanate a sense of friendship toward one creature you can see within range. The target must succeed on a Wisdom saving throw or have the Charmed condition for the duration. The target succeeds automatically if it isn't Humanoid, if you are fighting it, or if you have cast this spell on it within the past 24 hours.\n\nThe spell ends early if the target takes damage or if you make an attack roll, deal damage, or force anyone to make a saving throw. When the spell ends, the target knows it was Charmed by you.\n\n**Charmed (S.363):** Can't attack the Charmer, or target them with damage abilities/magical effects), Advantage on social interaction ability checks",
    material: "some makeup",
    school: "Enchantment",
    classes: "Bard, Sorcerer, Warlock, Wizard",
    id: "a947f80b",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Mind Sliver",
    level: 0,
    range: "60 feet",
    components: "V",
    duration: "1 round",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You try to temporarily sliver the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 Psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.\n\n**Cantrip Upgrade.** The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6) and 17 (4d6).",
    material: null,
    school: "Enchantment",
    classes: "Sorcerer, Warlock, Wizard",
    id: "084ec075",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Thunderclap",
    level: 0,
    range: "Self",
    components: "S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "Each creature in a 5-foot Emanation originating from you must succeed on a Constitution saving throw or take 1d6 Thunder damage. The spell's thunderous sound can be heard up to 100 feet away.\n\n**Cantrip Upgrade.** The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6) and 17 (4d6).",
    material: null,
    school: "Evocation",
    classes: "Bard, Druid, Sorcerer, Warlock, Wizard",
    id: "12405994",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Toll the Dead",
    level: 0,
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You point at one creature you can see within range, and the single chime of a dolorous bell is audible within 10 feet of the target. The target must succeed on a Wisdom saving throw or take 1d8 Necrotic damage. If the target is missing any of its Hit Points, it instead takes 1d12 Necrotic damage.\n\n**Cantrip Upgrade.** The damage increases by one die when you reach levels 5 (2d8 or 2d12), 11 (3d8 or 3d12), and 17 (4d8 or 4d12).",
    material: null,
    school: "Necromancy",
    classes: "Cleric, Warlock, Wizard",
    id: "c0418252",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Tasha's Hideous Laughter",
    level: 1,
    range: "30 feet",
    components: "V, S, M",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "One creature of your choice that you can see within range makes a Wisdom saving throw. On a failed save, it has the Prone and Incapacitated conditions for the duration. During that time, it laughs uncontrollably if it’s capable of laughter, and it can’t end the Prone condition on itself.\n\nAt the end of each of its turns and each time it takes damage, it makes another Wisdom saving throw. The target has Advantage on the save if the save is triggered by damage. On a successful save, the spell ends.\n\n**Using a Higher-Level Spell Slot.** You can target one additional creature for each spell slot level about 1.",
    material: "A tart and a feather",
    school: "Enchantment",
    classes: "Bard, Warlock, Wizard",
    id: "798fc2d8",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Witch Bolt",
    level: 1,
    range: "60 feet",
    components: "V, S, M",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "A beam of crackling energy lances toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against it. On a hit, the target takes 2d12 Lightning damage.\n\nOn each of your subsequent turns, you can take a Bonus Action to deal 1d12 Lightning damage to the target automatically, even if the first attack missed.\n\nThe spell ends if the target is ever outside the spell’s range or if it has Total Cover from you.\n\n**Using a Higher-Level Spell Slot.**  The initial damage increases by 1d12 for each spell slot level above 1.",
    material: "A twig struck by lightning",
    school: "Evocation",
    classes: "Sorcerer, Warlock, Wizard",
    id: "3e99ca3e",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Armor of Agathys",
    level: 1,
    range: "Self",
    components: "V, S, M",
    duration: "1 hour",
    concentration: false,
    casting_time: "Bonus Action",
    ritual: false,
    description:
      "Protective magical frost surrounds you. You gain 5 Temporary Hit Points. If a creature hits you with a meele attack roll before the spell ends, the create takes 5 Cold damage. The spell ends early if you have no Temporary Hit Points.\n\n**Using a Higher-Level Spell Slot.** The Temporary Hit Points and the Cold damage both increase by 5 for each spell slot level above 1.",
    material: "a shard of blue glass",
    school: "Abjuration",
    classes: "Warlock",
    id: "98785ae0",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Arms of Hadar",
    level: 1,
    range: "Self",
    components: "V, S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "Invoking Hadar, you cause tendrils to erupt from yourself. Each creature in a 10-foot Emanation originating from you makes a Strength saving throw. On a failed save, a target takes 2d6 Necrotic damage amd can't take Reactions until the start of its next turn. On a successful save, a target takes half as much damage only.\n\n**Using a Higher-Level Spell Slot.** The damage increases by 1d6 for each spell slot level above 1.",
    material: null,
    school: "Conjuration",
    classes: "Warlock",
    id: "99759d8d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Compelled Duel",
    level: 1,
    range: "30 feet",
    components: "V",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Bonus Action",
    ritual: false,
    description:
      "You try to compel a creature into a duel. One creature that you can see within range makes a Wisdom saving throw. On a failed save, the target has Disadvantage on attack rolls against creatures other than you, and it can't willingly move to a space that is more than 30 feet away from you.\n\nThe spell ends if you make an attack roll against a creature other than the target, if an ally of yours damages the target, or if you end your turn more than 30 feet away from the target.",
    material: null,
    school: "Enchantment",
    classes: "Paladin",
    id: "37819c30",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Hail of Thorns",
    level: 1,
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Bonus Action*",
    ritual: false,
    description:
      "*) which you take immediately after hitting a creature with a Ranged weapon\n\nAs you hit the creature, this spell creates a rain of thorns that sprouts from your Ranged weapon or ammunition. The target of the attack and each creature within 5 feet of it make a Dexterity saving throw, taking 1d10 Piercing damage on a failed save or half as much damage on a successful one.\n\n**Using a Higher-Level Spell Slot.** The damage increases by 1d10 for each spell slot level above 1.",
    material: null,
    school: "Conjuration",
    classes: "Ranger",
    id: "e9d3610d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Thorn Whip",
    level: 0,
    range: "30 feet",
    components: "V, S, M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You create a vine-like whip covered in thorns that lashes out at your command towards a create in range. Make a meele spell attack against the target. On a hit, the target takes 1d6 Piercing damage, and if it is Large or smaller, you can pull it up to 10 feet closer to you.\n\n**Cantrip Upgrade.** The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    material: "the stem of a thorny plant",
    school: "Transmutation",
    classes: "Druid",
    id: "00e7c32d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Thunderous Smite",
    level: 1,
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Bonus Action*",
    ritual: false,
    description:
      "*) which you take immediately after hitting a target with a Meele weapon or Unarmed Strike\n\nYour strike rings with thunder that is audible within 300 feet of you, and the target takes an extra 2d6 Thunder damage from the attack. Additionally, if the target is a create, it must succeed on a Strength saving throw or be pushed 10 feet away from you and have the Prone condition.\n\n**Using a Higher-Level Spell Slot.** The damage increases by 1d6 for each spell slot level above 1.",
    material: null,
    school: "Evocation",
    classes: "Paladin",
    id: "ebb74952",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Word of Radiance",
    level: 0,
    range: "Self",
    components: "V, M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "Burning radiance erupts from you in a 5-foot Emanation. Each creature of your choice that you can see in it must succeed on a Constitution saving throw or take 1d6 Radiant damage.\n\n**Cantrip Upgrade.** The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    material: "a sunburst token",
    school: "Evocation",
    classes: "Cleric",
    id: "2212ce40",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Wrathful Smite",
    level: 1,
    range: "Self",
    components: "V",
    duration: "1 minute",
    concentration: false,
    casting_time: "Bonus Action*",
    ritual: false,
    description:
      "*) which you take immediately after hitting a target with a Meele weapon or Unarmed Strike\n\nThe target takes an extra 1d6 Necrotic damage from the attack, and it must succeed on a Wisdom saving throw or have the Frightened condition until the spell ends. At the end of each of its turns, the Frightened target repeats the save, ending the spell on itself on a success.\n\n**Using a Higher-Level Spell Slot.** The damage increases by 1d6 for each spell slot level above 1.",
    material: null,
    school: "Necromancy",
    classes: "Paladin",
    id: "629d21aa",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Control Flames (2014)",
    level: 0,
    range: "60 feet",
    components: "S",
    duration: "Instantaneous/1h",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You choose nonmagical flame that you can see within range and that fits within a 5-foot cube. You affect it in one of the following ways:\n\n* You instantaneously expand the flame 5 feet in one direction, provided that wood or other fuel is present in the new location.\n* You instantaneously extinguish the flames within the cube.\n* You double or halve the area of bright light and dim light cast by the flame, change its color, or both. The change lasts for 1 hour.\n* You cause simple shapes—such as the vague form of a creature, an inanimate object, or a location—to appear within the flames and animate as you like. The shapes last for 1 hour.\n\nIf you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
    material: null,
    school: "Transmutation",
    classes: "Wizard, Druid, Sorcerer",
    id: "e89cfce3",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Create Bonfire (2014)",
    level: 0,
    range: "60 feet",
    components: "V,S",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "You create a bonfire on ground that you can see within range. Until the spell ends, the bonfire fills a 5-foot cube. Any creature in the bonfire’s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage. A creature must also make the saving throw when it enters the bonfire’s space for the first time on a turn or ends its turn there.\n\n**At Higher Levels.** The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    material: null,
    school: "Conjuration",
    classes: "Wizard, Artificer, Druid, Sorcerer, Warlock",
    id: "ba4a326d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Frostbite (2014)",
    level: 0,
    range: "60 feet",
    components: "V,S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: null,
    ritual: false,
    description:
      "You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.\n\n**At Higher Levels.** The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
    material: null,
    school: "Evocation",
    classes: "Wizard, Druid, Sorcerer, Warlock, Artificer",
    id: "bc973652",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Gust (2014)",
    level: 0,
    range: "30 feet",
    components: "V,S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You seize the air and compel it to create one of the following effects at a point you can see within range:\n\n* One Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 5 feet away from you.\n* You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. The object is pushed up to 10 feet away from you. It isn’t pushed with enough force to cause damage.\n* You create a harmless sensory affect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.",
    material: null,
    school: "Transmutation",
    classes: "Wizard, Druid, Sorcerer",
    id: "fcb69d36",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Infestation (2014)",
    level: 0,
    range: "30 feet",
    components: "V,S,M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: null,
    ritual: false,
    description:
      "You cause a cloud of mites, fleas, and other parasites to appear momentarily on one creature you can see within range. The target must succeed on a Constitution saving throw, or it takes 1d6 poison damage and moves 5 feet in a random direction if it can move and its speed is at least 5 feet. Roll a d4 for the direction: 1, north; 2, south; 3, east; or 4, west. This movement doesn’t provoke opportunity attacks, and if the direction rolled is blocked, the target doesn't move.\n\n**At Higher Levels.** The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
    material: "living flea",
    school: "Conjuration",
    classes: "Wizard, Druid, Sorcerer, Warlock",
    id: "3f6a9fff",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Mold Earth (2014)",
    level: 0,
    range: "30 feet",
    components: "S",
    duration: "Instantaneous/1h",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You choose a portion of dirt or stone that you can see within range and that fits within a 5-foot cube. You manipulate it in one of the following ways:\n\n* If you target an area of loose earth, you can instantaneously excavate it, move it along the ground, and deposit it up to 5 feet away. This movement doesn’t have enough force to cause damage.\n* You cause shapes, colors, or both to appear on the dirt or stone, spelling out words, creating images, or shaping patterns. The changes last for 1 hour.\n* If the dirt or stone you target is on the ground, you cause it to become difficult terrain. Alternatively, you can cause the ground to become normal terrain if it is already difficult terrain. This change lasts for 1 hour.\n\nIf you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
    material: null,
    school: "Transmutation",
    classes: "Wizard, Druid, Sorcerer",
    id: "ab4dc58f",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Shape Water (2014)",
    level: 0,
    range: "30 feet",
    components: "S",
    duration: "Instantaneous/1h",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You choose an area of water that you can see within range and that fits within a 5-foot cube. You manipulate it in one of the following ways:\n\n* You instantaneously move or otherwise change the flow of the water as you direct, up to 5 feet in any direction. This movement doesn’t have enough force to cause damage.\n\n* You cause the water to form into simple shapes and animate at your direction. This change lasts for 1 hour.\n\n* You change the water’s color or opacity. The water must be changed in the same way throughout. This change lasts for 1 hour.\n\n* You freeze the water, provided that there are no creatures in it. The water unfreezes in 1 hour.\n\nIf you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
    material: null,
    school: "Transmutation",
    classes: "Wizard, Druid, Sorcerer",
    id: "60c72151",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Absorb Elements (2014)",
    level: 1,
    range: "Self",
    components: "S",
    duration: "1 round",
    concentration: false,
    casting_time: "Reaction*",
    ritual: false,
    description:
      "*) which you take when you take acid, cold, fire, lightning, or thunder damage\n\nThe spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.\n\n**At Higher Levels.** When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.",
    material: null,
    school: "Abjuration",
    classes: "Wizard, Artificer, Druid, Ranger, Sorcerer",
    id: "9a2e1193",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Catapult (2014)",
    level: 1,
    range: "60 feet",
    components: "S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "Choose one object weighing 1 to 5 pounds within range that isn’t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. When the object strikes something, the object and what it strikes each take 3d8 bludgeoning damage.\n\n**At Higher Levels.** When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.",
    material: null,
    school: "Transmutation",
    classes: "Wizard, Sorcerer, Artificer",
    id: "f54c07c9",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Cause Fear (2014)",
    level: 1,
    range: "60 feet",
    components: "V",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "You awaken the sense of mortality in one creature you can see within range. A construct or an undead is immune to this effect. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n\n**At Higher Levels.** When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.",
    material: null,
    school: "Necromancy",
    classes: "Wizard, Warlock",
    id: "86ded5c1",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Earth Tremor (2014)",
    level: 1,
    range: "Self",
    components: "V,S",
    duration: "Instantaneous",
    concentration: false,
    casting_time: null,
    ritual: false,
    description:
      "You cause a tremor in the ground in a 10-foot radius. Each creature other than you in that area must make a Dexterity saving throw. On a failed save, a creature takes 1d6 bludgeoning damage and is knocked prone. If the ground in that area is loose earth or stone, it becomes difficult terrain until cleared.\n\n**At Higher Levels.** When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    material: null,
    school: "Evocation",
    classes: "Wizard, Bard, Druid, Sorcerer",
    id: "c9486ada",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Snare (2014)",
    level: 1,
    range: "Touch",
    components: "S,M",
    duration: "8 hours",
    concentration: false,
    casting_time: "1 minute",
    ritual: false,
    description:
      "As you cast this spell, you use the rope to create a circle with a 5-foot radius on the ground or the floor. When you finish casting, the rope disappears and the circle becomes a magic trap.\n\nThis trap is nearly invisible, requiring a successful Intelligence (Investigation) check against your spell save DC to be discerned.\n\nThe trap triggers when a Small, Medium, or Large creature moves onto the ground or the floor in the spell’s radius. That creature must succeed on a Dexterity saving throw or be magically hoisted into the air, leaving it hanging upside down 3 feet above the ground or the floor. The creature is restrained there until the spell ends.\n\nA restrained creature can make a Dexterity saving throw at the end of each of its turns, ending the effect on itself on a success. Alternatively, the creature or someone else who can reach it can use an action to make an Intelligence (Arcana) check against your spell save DC. On a success, the restrained effect ends.\n\nAfter the trap is triggered, the spell ends when no creature is restrained by it.",
    material: null,
    school: "Abjuration",
    classes: "Wizard, Artificer, Druid, Ranger",
    id: "2f143a9b",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Booming Blade (2014)",
    level: 0,
    range: "Self",
    components: "S,M",
    duration: "1 round",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You brandish the weapon used in the spell’s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack’s normal effects and then becomes sheathed in booming energy until the start of your next turn. If the target willingly moves 5 feet or more before then, the target takes 1d8 thunder damage, and the spell ends.\n\n**At Higher Levels.** At 5th level, the melee attack deals an extra 1d8 thunder damage to the target on a hit, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level (2d8 and 3d8) and again at 17th level (3d8 and 4d8).",
    material: "melee weapon worth at least 1 sp",
    school: "Evocation",
    classes: "Artificer, Sorcerer, Warlock, Wizard",
    id: "9d5632fd",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Green-Flame Blade (2014)",
    level: 0,
    range: "Self",
    components: "S, M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You brandish the weapon used in the spell’s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack’s normal effects, and you can cause green fire to leap from the target to a different creature of your choice that you can see within 5 feet of it. The second creature takes fire damage equal to your spellcasting ability modifier.\n\n**At Higher Levels.** At 5th level, the melee attack deals an extra 1d8 fire damage to the target on a hit, and the fire damage to the second creature increases to 1d8 + your spellcasting ability modifier. Both damage rolls increase by 1d8 at 11th level (2d8 and 2d8) and 17th level (3d8 and 3d8).",
    material: "melee weapon worth at least 1 sp",
    school: "Evocation",
    classes: "Artificer, Sorcerer, Warlock, Wizard",
    id: "43a59d32",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Lightning Lure (2014)",
    level: 0,
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You create a lash of lightning energy that strikes at one creature of your choice that you can see within 15 feet of you. The target must succeed on a Strength saving throw or be pulled up to 10 feet in a straight line toward you and then take 1d8 lightning damage if it is within 5 feet of you.\n\n**At Higher Levels.** This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    material: null,
    school: "Evocation",
    classes: "Artificer, Sorcerer, Warlock, Wizard",
    id: "a0d856e4",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Sword Burst (2014)",
    level: 0,
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You create a momentary circle of spectral blades that sweep around you. All other creatures within 5 feet of you must succeed on a Dexterity saving throw or take 1d6 force damage.\n\n**At Higher Levels.** This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
    material: null,
    school: "Conjuration",
    classes: "Artificer, Sorcerer, Warlock, Wizard",
    id: "dec9b9e3",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Astral Flood",
    level: 3,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: null,
    material: null,
    school: null,
    classes: null,
    id: "e466eded",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Buzzing Bee",
    level: 1,
    range: "120 feet",
    components: "V,S,M",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "You call forth a noisy spectral bee. You target a creature that you can see within range. The bee hovers around the target, distracting it with loud buzzing. For the duration, the target has Disadvantage on Wisdom (Perception) checks, Dexterity (Stealth) checks, and Constitution saving throws made to maintain Concentration. In addition, the target cannot benefit from the Invisible condition.\n\nThe bee moves with the target, hovering within 3 feet of it as long as the target is within 120 feet of you. The bee disappears when the spell ends or if the target moves out of range.",
    material: "a dab of honey",
    school: "Conjuration",
    classes: "Druid, Ranger, Sorcerer, Wizard",
    id: "eca6334f",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Insidious Rythm",
    level: 1,
    range: "120 feet",
    components: "V,S",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Action",
    ritual: false,
    description:
      "One creature of your choice that you can see within range hears a haunting yet catchy tune that continuously repeats in its mind. The target must succeed on a Wisdom saving throw, or it has Disadvantage on Intelligence checks and on Constitution saving throws made to maintain Concentration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success.\n\n**Using a Higher-Level Spell Slot.** You can target one additional creature for each spell slot level above 1.",
    material: null,
    school: "Enchantment",
    classes: "Bard",
    id: "e0ca9044",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Leomund's Lamentable Belaborment",
    level: 6,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description:
      "http://dnd2024.wikidot.com/spell:leomund-s-lamentable-belaborment",
    material: null,
    school: null,
    classes: null,
    id: "13cedf20",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Searing Orb",
    level: 2,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "http://dnd2024.wikidot.com/spell:searing-orb",
    material: null,
    school: null,
    classes: null,
    id: "4e639b15",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Sticks to Snakes",
    level: 4,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "http://dnd2024.wikidot.com/spell:sticks-to-snakes",
    material: null,
    school: null,
    classes: null,
    id: "ad1b35f8",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Tortoise Shell",
    level: 2,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "http://dnd2024.wikidot.com/spell:tortoise-shell",
    material: null,
    school: null,
    classes: null,
    id: "e8ebe897",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Void Star",
    level: 7,
    range: "120 feet",
    components: "V,S,M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You conjure forth a fragment of a dark star and launch it at one creature that you can see within range. Make a ranged spell attack against the target. On a hit, the target takes 6d12 Necrotic damage. At the end of the target’s next turn, it takes 3d12 Necrotic damage, and you regain Hit Points equal to the amount of Necrotic damage dealt.\n\n**Using a Higher-Level Spell Slot.** The damage (both initial and later) increases by 1d12 for each spell slot level above 7.",
    material: "a fragment of a meteor",
    school: "Necromancy",
    classes: "Wizard, Warlock",
    id: "d494c88d",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Cloud of Daggers",
    level: 2,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "https://dnd5e.wikidot.com/spell:cloud-of-daggers",
    material: null,
    school: null,
    classes: "Wizard",
    id: "ca83e56e",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Crown of Madness",
    level: 2,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "https://dnd5e.wikidot.com/spell:crown-of-madness",
    material: null,
    school: null,
    classes: "Wizard",
    id: "74ccc546",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Shadow Blade",
    level: 2,
    range: "Self",
    components: "V,S",
    duration: "Up to 1 Minute",
    concentration: true,
    casting_time: "Bonus Action",
    ritual: false,
    description:
      "You weave together threads of shadow to create a sword of solidified gloom in your hand. This magic sword lasts until the spell ends. It counts as a simple melee weapon with which you are proficient. It deals 2d8 psychic damage on a hit and has the finesse, light, and thrown properties (range 20/60). In addition, when you use the sword to attack a target that is in dim light or darkness, you make the attack roll with advantage.\n\nIf you drop the weapon or throw it, it dissipates at the end of the turn. Thereafter, while the spell persists, you can use a bonus action to cause the sword to reappear in your hand.\n\n**At Higher Levels.** When you cast this spell using a 3rd- or 4th-level spell slot, the damage increases to 3d8. When you cast it using a 5th- or 6th-level spell slot, the damage increases to 4d8. When you cast it using a spell slot of 7th level or higher, the damage increases to 5d8.",
    material: null,
    school: "Illusion",
    classes: "Wizard, Sorcerer, Warlock",
    id: "f3c2a1e0",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Tasha's Mind Whip",
    level: 2,
    range: null,
    components: null,
    duration: null,
    concentration: false,
    casting_time: null,
    ritual: false,
    description: "https://dnd5e.wikidot.com/spell:tashas-mind-whip",
    material: null,
    school: null,
    classes: "Wizard",
    id: "c03c565f",
    custom_data: true,
    card_type: "SPELL",
  },
  {
    spell_name: "Wither and Bloom",
    level: 2,
    range: "60 feet",
    components: "V,S,M",
    duration: "Instantaneous",
    concentration: false,
    casting_time: "Action",
    ritual: false,
    description:
      "You invoke both death and life upon a 10-foot-radius sphere centered on a point within range. Each creature of your choice in that area must make a Constitution saving throw, taking 2d6 necrotic damage on a failed save, or half as much damage on a successful one. Nonmagical vegetation in that area withers.\n\nIn addition, one creature of your choice in that area can spend and roll one of its unspent Hit Dice and regain a number of hit points equal to the roll plus your spellcasting ability modifier.\n\n**At Higher Levels.** When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot above 2nd, and the number of Hit Dice that can be spent and added to the healing roll increases by one for each slot above 2nd.",
    material: "a withered vine twisted into a loop",
    school: "Necromancy",
    classes: "Druid, Sorcerer, Wizard",
    id: "eedb67ef",
    custom_data: true,
    card_type: "SPELL",
  },
];
